version: '3'

services:
  mysql-docker:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ilovemealplanning1[]
    networks:
      - db_nw
  flask:
    volumes:
      - ./:/usr/src/GetTheGroceries/
    build:
      context: ./
      dockerfile: ./flask/Dockerfile
    expose:
      - "5000"
    depends_on:
      - mysql-docker
    networks:
      - db_nw
      - web_nw
  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    volumes:
      - ./static:/usr/src/GetTheGroceries/static
      - ../nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ../dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./nginx/www.getthegroceries.io.conf:/etc/nginx/conf.d/www.getthegroceries.io.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_nw
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
