version: '3'

services:
  mysql-docker:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ilovemealplanning1[]
    networks:
      - db_nw
  flask:
    volumes:
      - ./:/usr/src/GetTheGroceries/
    build:
      context: ./
      dockerfile: ./flask/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql-docker
    networks:
      - db_nw
      - web_nw
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    volumes:
      - ./static:/usr/src/GetTheGroceries/static
      - ./ssl:/usr/src/GetTheGroceries/ssl
      - ./nginx/getthegroceries.conf:/etc/nginx/conf.d/getthegroceries.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_nw
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge