version: '3'

services:
  mysql-docker:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ilovemealplanning1[]
    networks:
      - db_nw
  flask:
    build:
      context: ./
      dockerfile: ./flask/Dockerfile
    expose:
      - "5000"
    depends_on:
      - mysql-docker
    networks:
      - db_nw
      - web_nw
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "4567:443"
    depends_on:
      - flask
    volumes:
      - ./GetTheGroceries:/usr/src/GetTheGroceries
      - ./nginx/getthegroceries.conf:/etc/nginx/conf.d/getthegroceries.conf
    networks:
      - web_nw
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge